# Generated by Django 4.2 on 2024-11-23 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('savol_turi', models.CharField(choices=[('ASN', 'Asonroq Savol'), ('ORT', "O'rtacha Savol"), ('QYN', 'Qiyin Savol')], default='ORT', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='savol/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('fan_yoke_mavzu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.fanmavzusi')),
            ],
        ),
        migrations.CreateModel(
            name='Varyant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
                ('tugri_yoke_natugri', models.BooleanField(default=False, help_text="To'g'ri varionad bo'lsa ptichka qo'ying!!")),
                ('image', models.ImageField(blank=True, null=True, upload_to='savol/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('savol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.savol')),
            ],
        ),
    ]
