name: Publish Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Faqat 'main' branchga o'zgartirishlar qilinganda ishga tushadi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repositoryni klonlash
      - name: Checkout repository
        uses: actions/checkout@v3

      # Docker uchun o'rnatish
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker Hub'ga tizimga kirish
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_PASSWORD }}
          password: ${{ secrets.DOCKER_USERNAME }}

      # Docker imidjini yaratish va push qilish
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_PASSWORD }}/django-quiz:latest
